In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("churn.csv")
df

customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1   
1     5575-GNVDE    Male              0      No         No      34   
2     3668-QPYBK    Male              0      No         No       2   
3     7795-CFOCW    Male              0      No         No      45   
4     9237-HQITU  Female              0      No         No       2   
...          ...     ...            ...     ...        ...     ...   
7038  6840-RESVB    Male              0     Yes        Yes      24   
7039  2234-XADUH  Female              0     Yes        Yes      72   
7040  4801-JZAZL  Female              0     Yes        Yes      11   
7041  8361-LTMKD    Male              1     Yes         No       4   
7042  3186-AJIEK    Male              0      No         No      66   

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL             No  ...   
1             Yes                No             DSL            Yes  ...   
2             Yes                No             DSL            Yes  ...   
3              No  No phone service             DSL            Yes  ...   
4             Yes                No     Fiber optic             No  ...   
...           ...               ...             ...            ...  ...   
7038          Yes               Yes             DSL            Yes  ...   
7039          Yes               Yes     Fiber optic             No  ...   
7040           No  No phone service             DSL            Yes  ...   
7041          Yes               Yes     Fiber optic             No  ...   
7042          Yes                No     Fiber optic            Yes  ...   

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month   
1                 Yes          No          No              No        One year   
2                  No          No          No              No  Month-to-month   
3                 Yes         Yes          No              No        One year   
4                  No          No          No              No  Month-to-month   
...               ...         ...         ...             ...             ...   
7038              Yes         Yes         Yes             Yes        One year   
7039              Yes          No         Yes             Yes        One year   
7040               No          No          No              No  Month-to-month   
7041               No          No          No              No  Month-to-month   
7042              Yes         Yes         Yes             Yes        Two year   

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0                 Yes           Electronic check          29.85         29.85   
1                  No               Mailed check          56.95        1889.5   
2                 Yes               Mailed check          53.85        108.15   
3                  No  Bank transfer (automatic)          42.30       1840.75   
4                 Yes           Electronic check          70.70        151.65   
...               ...                        ...            ...           ...   
7038              Yes               Mailed check          84.80        1990.5   
7039              Yes    Credit card (automatic)         103.20        7362.9   
7040              Yes           Electronic check          29.60        346.45   
7041              Yes               Mailed check          74.40         306.6   
7042              Yes  Bank transfer (automatic)         105.65        6844.5   

     Churn  
0       No  
1       No  
2      Yes  
3       No  
4      Yes  
...    ...  
7038    No  
7039    No  
7040    No  
7041   Yes  
7042    No  

[7043 rows x 21 columns]

In [3]:
df.columns = df.columns.str.lower().str.replace(" ", "_")
df

customerid  gender  seniorcitizen partner dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1   
1     5575-GNVDE    Male              0      No         No      34   
2     3668-QPYBK    Male              0      No         No       2   
3     7795-CFOCW    Male              0      No         No      45   
4     9237-HQITU  Female              0      No         No       2   
...          ...     ...            ...     ...        ...     ...   
7038  6840-RESVB    Male              0     Yes        Yes      24   
7039  2234-XADUH  Female              0     Yes        Yes      72   
7040  4801-JZAZL  Female              0     Yes        Yes      11   
7041  8361-LTMKD    Male              1     Yes         No       4   
7042  3186-AJIEK    Male              0      No         No      66   

     phoneservice     multiplelines internetservice onlinesecurity  ...  \
0              No  No phone service             DSL             No  ...   
1             Yes                No             DSL            Yes  ...   
2             Yes                No             DSL            Yes  ...   
3              No  No phone service             DSL            Yes  ...   
4             Yes                No     Fiber optic             No  ...   
...           ...               ...             ...            ...  ...   
7038          Yes               Yes             DSL            Yes  ...   
7039          Yes               Yes     Fiber optic             No  ...   
7040           No  No phone service             DSL            Yes  ...   
7041          Yes               Yes     Fiber optic             No  ...   
7042          Yes                No     Fiber optic            Yes  ...   

     deviceprotection techsupport streamingtv streamingmovies        contract  \
0                  No          No          No              No  Month-to-month   
1                 Yes          No          No              No        One year   
2                  No          No          No              No  Month-to-month   
3                 Yes         Yes          No              No        One year   
4                  No          No          No              No  Month-to-month   
...               ...         ...         ...             ...             ...   
7038              Yes         Yes         Yes             Yes        One year   
7039              Yes          No         Yes             Yes        One year   
7040               No          No          No              No  Month-to-month   
7041               No          No          No              No  Month-to-month   
7042              Yes         Yes         Yes             Yes        Two year   

     paperlessbilling              paymentmethod monthlycharges  totalcharges  \
0                 Yes           Electronic check          29.85         29.85   
1                  No               Mailed check          56.95        1889.5   
2                 Yes               Mailed check          53.85        108.15   
3                  No  Bank transfer (automatic)          42.30       1840.75   
4                 Yes           Electronic check          70.70        151.65   
...               ...                        ...            ...           ...   
7038              Yes               Mailed check          84.80        1990.5   
7039              Yes    Credit card (automatic)         103.20        7362.9   
7040              Yes           Electronic check          29.60        346.45   
7041              Yes               Mailed check          74.40         306.6   
7042              Yes  Bank transfer (automatic)         105.65        6844.5   

     churn  
0       No  
1       No  
2      Yes  
3       No  
4      Yes  
...    ...  
7038    No  
7039    No  
7040    No  
7041   Yes  
7042    No  

[7043 rows x 21 columns]

In [4]:
categorical_columns= df.dtypes[df.dtypes== 'object']
categorical_columns = list(categorical_columns.index)
categorical_columns

['customerid',
 'gender',
 'partner',
 'dependents',
 'phoneservice',
 'multiplelines',
 'internetservice',
 'onlinesecurity',
 'onlinebackup',
 'deviceprotection',
 'techsupport',
 'streamingtv',
 'streamingmovies',
 'contract',
 'paperlessbilling',
 'paymentmethod',
 'totalcharges',
 'churn']

In [5]:
for i in categorical_columns :
    df[i] = df[i].str.lower().str.replace(" ", "_")

In [6]:
df

customerid  gender  seniorcitizen partner dependents  tenure  \
0     7590-vhveg  female              0     yes         no       1   
1     5575-gnvde    male              0      no         no      34   
2     3668-qpybk    male              0      no         no       2   
3     7795-cfocw    male              0      no         no      45   
4     9237-hqitu  female              0      no         no       2   
...          ...     ...            ...     ...        ...     ...   
7038  6840-resvb    male              0     yes        yes      24   
7039  2234-xaduh  female              0     yes        yes      72   
7040  4801-jzazl  female              0     yes        yes      11   
7041  8361-ltmkd    male              1     yes         no       4   
7042  3186-ajiek    male              0      no         no      66   

     phoneservice     multiplelines internetservice onlinesecurity  ...  \
0              no  no_phone_service             dsl             no  ...   
1             yes                no             dsl            yes  ...   
2             yes                no             dsl            yes  ...   
3              no  no_phone_service             dsl            yes  ...   
4             yes                no     fiber_optic             no  ...   
...           ...               ...             ...            ...  ...   
7038          yes               yes             dsl            yes  ...   
7039          yes               yes     fiber_optic             no  ...   
7040           no  no_phone_service             dsl            yes  ...   
7041          yes               yes     fiber_optic             no  ...   
7042          yes                no     fiber_optic            yes  ...   

     deviceprotection techsupport streamingtv streamingmovies        contract  \
0                  no          no          no              no  month-to-month   
1                 yes          no          no              no        one_year   
2                  no          no          no              no  month-to-month   
3                 yes         yes          no              no        one_year   
4                  no          no          no              no  month-to-month   
...               ...         ...         ...             ...             ...   
7038              yes         yes         yes             yes        one_year   
7039              yes          no         yes             yes        one_year   
7040               no          no          no              no  month-to-month   
7041               no          no          no              no  month-to-month   
7042              yes         yes         yes             yes        two_year   

     paperlessbilling              paymentmethod monthlycharges  totalcharges  \
0                 yes           electronic_check          29.85         29.85   
1                  no               mailed_check          56.95        1889.5   
2                 yes               mailed_check          53.85        108.15   
3                  no  bank_transfer_(automatic)          42.30       1840.75   
4                 yes           electronic_check          70.70        151.65   
...               ...                        ...            ...           ...   
7038              yes               mailed_check          84.80        1990.5   
7039              yes    credit_card_(automatic)         103.20        7362.9   
7040              yes           electronic_check          29.60        346.45   
7041              yes               mailed_check          74.40         306.6   
7042              yes  bank_transfer_(automatic)         105.65        6844.5   

     churn  
0       no  
1       no  
2      yes  
3       no  
4      yes  
...    ...  
7038    no  
7039    no  
7040    no  
7041   yes  
7042    no  

[7043 rows x 21 columns]

In [7]:
df.dtypes

customerid           object
gender               object
seniorcitizen         int64
partner              object
dependents           object
tenure                int64
phoneservice         object
multiplelines        object
internetservice      object
onlinesecurity       object
onlinebackup         object
deviceprotection     object
techsupport          object
streamingtv          object
streamingmovies      object
contract             object
paperlessbilling     object
paymentmethod        object
monthlycharges      float64
totalcharges         object
churn                object
dtype: object

In [8]:
## Total charges should be a numeric object not string object.
df["totalcharges"]= pd.to_numeric(df["totalcharges"], errors= "coerce")

In [9]:
df.dtypes

customerid           object
gender               object
seniorcitizen         int64
partner              object
dependents           object
tenure                int64
phoneservice         object
multiplelines        object
internetservice      object
onlinesecurity       object
onlinebackup         object
deviceprotection     object
techsupport          object
streamingtv          object
streamingmovies      object
contract             object
paperlessbilling     object
paymentmethod        object
monthlycharges      float64
totalcharges        float64
churn                object
dtype: object

In [10]:
df.totalcharges.isnull().sum()

np.int64(11)

In [11]:
df.totalcharges = df.totalcharges.fillna(0)

In [12]:
df.totalcharges.isnull().sum()

np.int64(0)

In [13]:
df.isnull().sum()

customerid          0
gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        0
churn               0
dtype: int64

### Convert the churn to 1s and 0s for binary classification. Yes=1, No=0

In [14]:
df.churn = (df.churn == "yes").astype(int)

In [15]:
df.churn

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: churn, Length: 7043, dtype: int64

In [16]:
df

customerid  gender  seniorcitizen partner dependents  tenure  \
0     7590-vhveg  female              0     yes         no       1   
1     5575-gnvde    male              0      no         no      34   
2     3668-qpybk    male              0      no         no       2   
3     7795-cfocw    male              0      no         no      45   
4     9237-hqitu  female              0      no         no       2   
...          ...     ...            ...     ...        ...     ...   
7038  6840-resvb    male              0     yes        yes      24   
7039  2234-xaduh  female              0     yes        yes      72   
7040  4801-jzazl  female              0     yes        yes      11   
7041  8361-ltmkd    male              1     yes         no       4   
7042  3186-ajiek    male              0      no         no      66   

     phoneservice     multiplelines internetservice onlinesecurity  ...  \
0              no  no_phone_service             dsl             no  ...   
1             yes                no             dsl            yes  ...   
2             yes                no             dsl            yes  ...   
3              no  no_phone_service             dsl            yes  ...   
4             yes                no     fiber_optic             no  ...   
...           ...               ...             ...            ...  ...   
7038          yes               yes             dsl            yes  ...   
7039          yes               yes     fiber_optic             no  ...   
7040           no  no_phone_service             dsl            yes  ...   
7041          yes               yes     fiber_optic             no  ...   
7042          yes                no     fiber_optic            yes  ...   

     deviceprotection techsupport streamingtv streamingmovies        contract  \
0                  no          no          no              no  month-to-month   
1                 yes          no          no              no        one_year   
2                  no          no          no              no  month-to-month   
3                 yes         yes          no              no        one_year   
4                  no          no          no              no  month-to-month   
...               ...         ...         ...             ...             ...   
7038              yes         yes         yes             yes        one_year   
7039              yes          no         yes             yes        one_year   
7040               no          no          no              no  month-to-month   
7041               no          no          no              no  month-to-month   
7042              yes         yes         yes             yes        two_year   

     paperlessbilling              paymentmethod monthlycharges  totalcharges  \
0                 yes           electronic_check          29.85         29.85   
1                  no               mailed_check          56.95       1889.50   
2                 yes               mailed_check          53.85        108.15   
3                  no  bank_transfer_(automatic)          42.30       1840.75   
4                 yes           electronic_check          70.70        151.65   
...               ...                        ...            ...           ...   
7038              yes               mailed_check          84.80       1990.50   
7039              yes    credit_card_(automatic)         103.20       7362.90   
7040              yes           electronic_check          29.60        346.45   
7041              yes               mailed_check          74.40        306.60   
7042              yes  bank_transfer_(automatic)         105.65       6844.50   

      churn  
0         0  
1         0  
2         1  
3         0  
4         1  
...     ...  
7038      0  
7039      0  
7040      0  
7041      1  
7042      0  

[7043 rows x 21 columns]

## Setting up validation framework with scikit learn

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
train_test_split?

Signature:
train_test_split(
    *arrays,
    test_size=None,
    train_size=None,
    random_state=None,
    shuffle=True,
    stratify=None,
)
Docstring:
Split arrays or matrices into random train and test subsets.

Quick utility that wraps input validation,
``next(ShuffleSplit().split(X, y))``, and application to input data
into a single call for splitting (and optionally subsampling) data into a
one-liner.

Read more in the :ref:`User Guide <cross_validation>`.

Parameters
----------
*arrays : sequence of indexables with same length / shape[0]
    Allowed inputs are lists, numpy arrays, scipy-sparse
    matrices or pandas dataframes.

test_size : float or int, default=None
    If float, should be between 0.0 and 1.0 and represent the proportion
    of the dataset to include in the test split. If int, represents the
    absolute number of test samples. If None, the value is set to the
    complement of the train size. If ``train_size`` is also None, it will
    be set to 0.25.

trai

In [19]:
df_full_train, df_test = train_test_split(df, test_size= 0.2, random_state= 1)

In [20]:
df_test

customerid  gender  seniorcitizen partner dependents  tenure  \
3381  8879-zkjof  female              0      no         no      41   
6180  0201-mibol  female              1      no         no      66   
4829  1600-dilpe  female              0      no         no      12   
3737  8601-qacrs  female              0      no         no       5   
4249  7919-zodzz  female              0     yes        yes      10   
...          ...     ...            ...     ...        ...     ...   
2563  5130-iekqt    male              1      no         no      25   
2028  4452-rohmo  female              0      no         no      15   
2899  6164-haqtx    male              0      no         no      71   
3474  3982-dqlus    male              1     yes        yes      65   
5154  9874-qlclh  female              0     yes        yes      17   

     phoneservice     multiplelines internetservice       onlinesecurity  ...  \
3381          yes                no             dsl                  yes  ...   
6180          yes               yes     fiber_optic                  yes  ...   
4829          yes                no             dsl                   no  ...   
3737          yes               yes             dsl                   no  ...   
4249          yes                no             dsl                   no  ...   
...           ...               ...             ...                  ...  ...   
2563          yes               yes     fiber_optic                   no  ...   
2028          yes                no              no  no_internet_service  ...   
2899           no  no_phone_service             dsl                  yes  ...   
3474          yes               yes     fiber_optic                  yes  ...   
5154          yes               yes     fiber_optic                  yes  ...   

         deviceprotection          techsupport          streamingtv  \
3381                  yes                  yes                  yes   
6180                   no                   no                  yes   
4829                   no                   no                   no   
3737                   no                   no                   no   
4249                  yes                   no                   no   
...                   ...                  ...                  ...   
2563                  yes                   no                  yes   
2028  no_internet_service  no_internet_service  no_internet_service   
2899                  yes                  yes                  yes   
3474                   no                   no                   no   
5154                  yes                   no                  yes   

          streamingmovies        contract paperlessbilling  \
3381                  yes        one_year              yes   
6180                  yes        two_year              yes   
4829                   no  month-to-month              yes   
3737                   no  month-to-month              yes   
4249                  yes        one_year              yes   
...                   ...             ...              ...   
2563                  yes  month-to-month               no   
2028  no_internet_service        two_year               no   
2899                   no        two_year               no   
3474                   no  month-to-month              yes   
5154                  yes  month-to-month              yes   

                  paymentmethod monthlycharges  totalcharges  churn  
3381  bank_transfer_(automatic)          79.85       3320.75      0  
6180  bank_transfer_(automatic)         102.40       6471.85      0  
4829  bank_transfer_(automatic)          45.00        524.35      0  
3737               mailed_check          50.60        249.95      1  
4249               mailed_check          65.90        660.05      0  
...                         ...            ...           ...    ...  
2563               mailed_check         105.95       2655.25      1  
2028               mailed_check   

In [21]:
df_train, df_val = train_test_split(df_full_train, test_size= 0.25, random_state= 1)

In [22]:
len(df_train), len(df_val), len(df_test)

(4225, 1409, 1409)

In [23]:
## Resetting indices
df_train = df_train.reset_index(drop = True)
df_val = df_val.reset_index(drop = True)
df_test = df_test.reset_index(drop = True)

In [24]:
y_train = df_train.churn.values
y_train

array([0, 0, 1, ..., 1, 0, 1])

In [25]:
del df_train["churn"]

In [26]:
df_train

customerid  gender  seniorcitizen partner dependents  tenure  \
0     8015-ihcgw  female              0     yes        yes      72   
1     1960-uycnn    male              0      no         no      10   
2     9250-wypll  female              0      no         no       5   
3     6786-obwqr  female              0     yes        yes       5   
4     1328-euzhc  female              0     yes         no      18   
...          ...     ...            ...     ...        ...     ...   
4220  1309-xgfsn    male              1     yes        yes      52   
4221  4819-hjpiw    male              0      no         no      18   
4222  3703-vavcl    male              0     yes        yes       2   
4223  3812-lrzir  female              0     yes        yes      27   
4224  1704-nrwye  female              1      no         no       9   

     phoneservice     multiplelines internetservice       onlinesecurity  \
0             yes               yes     fiber_optic                  yes   
1             yes               yes     fiber_optic                   no   
2             yes               yes     fiber_optic                   no   
3             yes                no     fiber_optic                   no   
4             yes                no              no  no_internet_service   
...           ...               ...             ...                  ...   
4220          yes               yes             dsl                   no   
4221           no  no_phone_service             dsl                   no   
4222          yes                no     fiber_optic                   no   
4223          yes               yes              no  no_internet_service   
4224          yes                no     fiber_optic                   no   

             onlinebackup     deviceprotection          techsupport  \
0                     yes                  yes                  yes   
1                     yes                  yes                   no   
2                      no                   no                   no   
3                      no                   no                   no   
4     no_internet_service  no_internet_service  no_internet_service   
...                   ...                  ...                  ...   
4220                  yes                  yes                   no   
4221                   no                   no                   no   
4222                   no                  yes                  yes   
4223  no_internet_service  no_internet_service  no_internet_service   
4224                   no                   no                   no   

              streamingtv      streamingmovies        contract  \
0                     yes                  yes        two_year   
1                      no                  yes  month-to-month   
2                      no                   no  month-to-month   
3                     yes                   no  month-to-month   
4     no_internet_service  no_internet_service        two_year   
...                   ...                  ...             ...   
4220                  yes                  yes        one_year   
4221                   no                   no  month-to-month   
4222                   no                  yes  month-to-month   
4223  no_internet_service  no_internet_service        two_year   
4224                  yes                   no  month-to-month   

     paperlessbilling            paymentmethod  monthlycharges  totalcharges  
0                 yes         electronic_check          115.50       8425.15  
1                 yes         electronic_check           95.25       1021.55  
2                  no         electronic_check           75.55        413.65  
3                 yes         electronic_check           80.85        356.10  
4                  no             mailed_check           20.10        370.50  
...               ...                      ...             ...           ...  
4220              yes         electronic_check       

In [27]:
y_val = df_val.churn.values
y_test = df_test.churn.values

In [28]:
del df_test["churn"]
del df_val["churn"]

## EXPLORATORY DATA ANALYSIS

In [29]:
# Missing values
df_full_train.isnull().sum()

customerid          0
gender              0
seniorcitizen       0
partner             0
dependents          0
tenure              0
phoneservice        0
multiplelines       0
internetservice     0
onlinesecurity      0
onlinebackup        0
deviceprotection    0
techsupport         0
streamingtv         0
streamingmovies     0
contract            0
paperlessbilling    0
paymentmethod       0
monthlycharges      0
totalcharges        0
churn               0
dtype: int64

In [30]:
df_full_train.churn.value_counts()

churn
0    4113
1    1521
Name: count, dtype: int64

In [31]:
df_full_train.churn.value_counts(normalize= True)

churn
0    0.730032
1    0.269968
Name: proportion, dtype: float64

In [32]:
globalchurnrate = df_full_train.churn.mean()
round(globalchurnrate, 2)

np.float64(0.27)

In [33]:
df_full_train.columns

Index(['customerid', 'gender', 'seniorcitizen', 'partner', 'dependents',
       'tenure', 'phoneservice', 'multiplelines', 'internetservice',
       'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
       'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling',
       'paymentmethod', 'monthlycharges', 'totalcharges', 'churn'],
      dtype='object')

In [34]:
numerical = ["tenure", "monthlycharges", "totalcharges"]
categorical = ['gender', 'seniorcitizen', 'partner', 'dependents', 'phoneservice', 'multiplelines', 'internetservice', 'onlinesecurity', 'onlinebackup', 'deviceprotection', 'techsupport',
'streamingtv', 'streamingmovies', 'contract', 'paperlessbilling','paymentmethod']

In [35]:
df_full_train[categorical].nunique()

gender              2
seniorcitizen       2
partner             2
dependents          2
phoneservice        2
multiplelines       3
internetservice     3
onlinesecurity      3
onlinebackup        3
deviceprotection    3
techsupport         3
streamingtv         3
streamingmovies     3
contract            3
paperlessbilling    2
paymentmethod       4
dtype: int64

In [36]:
## Churn rate per gender
churn_female = df_full_train[df_full_train.gender == "female"]. churn.mean()
churn_female

np.float64(0.27682403433476394)

In [37]:
churn_male = df_full_train[df_full_train.gender == "male"]. churn.mean()
churn_male

np.float64(0.2632135306553911)

In [38]:
## Churn rate per partner
df_full_train.partner.value_counts()

partner
no     2932
yes    2702
Name: count, dtype: int64

In [39]:
churn_partner = df_full_train[df_full_train.partner == "yes"]. churn.mean()
churn_partner

np.float64(0.20503330866025166)

In [40]:
churn_no_partner = df_full_train[df_full_train.partner == "no"]. churn.mean()
churn_no_partner

np.float64(0.3298090040927694)

Risk ratio = Average churn rate / global churn rate

In [41]:
from IPython.display import display

In [42]:
for c in categorical:
    print(c)
    df_group = df_full_train.groupby(c).churn.agg(["mean", "count"])
    df_group["diff"] = df_group ["mean"] - globalchurnrate
    df_group["risk"] = df_group["mean"] / globalchurnrate
    display(df_group)
    print()
    print()

gender


mean  count      diff      risk
gender                                     
female  0.276824   2796  0.006856  1.025396
male    0.263214   2838 -0.006755  0.974980



seniorcitizen


mean  count      diff      risk
seniorcitizen                                     
0              0.242270   4722 -0.027698  0.897403
1              0.413377    912  0.143409  1.531208



partner


mean  count      diff      risk
partner                                     
no       0.329809   2932  0.059841  1.221659
yes      0.205033   2702 -0.064935  0.759472



dependents


mean  count      diff      risk
dependents                                     
no          0.313760   3968  0.043792  1.162212
yes         0.165666   1666 -0.104302  0.613651



phoneservice


mean  count      diff      risk
phoneservice                                     
no            0.241316    547 -0.028652  0.893870
yes           0.273049   5087  0.003081  1.011412



multiplelines


mean  count      diff      risk
multiplelines                                        
no                0.257407   2700 -0.012561  0.953474
no_phone_service  0.241316    547 -0.028652  0.893870
yes               0.290742   2387  0.020773  1.076948



internetservice


mean  count      diff      risk
internetservice                                     
dsl              0.192347   1934 -0.077621  0.712482
fiber_optic      0.425171   2479  0.155203  1.574895
no               0.077805   1221 -0.192163  0.288201



onlinesecurity


mean  count      diff      risk
onlinesecurity                                          
no                   0.420921   2801  0.150953  1.559152
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.153226   1612 -0.116742  0.567570



onlinebackup


mean  count      diff      risk
onlinebackup                                            
no                   0.404323   2498  0.134355  1.497672
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.217232   1915 -0.052736  0.804660



deviceprotection


mean  count      diff      risk
deviceprotection                                        
no                   0.395875   2473  0.125907  1.466379
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.230412   1940 -0.039556  0.853480



techsupport


mean  count      diff      risk
techsupport                                             
no                   0.418914   2781  0.148946  1.551717
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.159926   1632 -0.110042  0.592390



streamingtv


mean  count      diff      risk
streamingtv                                             
no                   0.342832   2246  0.072864  1.269897
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.302723   2167  0.032755  1.121328



streamingmovies


mean  count      diff      risk
streamingmovies                                         
no                   0.338906   2213  0.068938  1.255358
no_internet_service  0.077805   1221 -0.192163  0.288201
yes                  0.307273   2200  0.037305  1.138182



contract


mean  count      diff      risk
contract                                           
month-to-month  0.431701   3104  0.161733  1.599082
one_year        0.120573   1186 -0.149395  0.446621
two_year        0.028274   1344 -0.241694  0.104730



paperlessbilling


mean  count      diff      risk
paperlessbilling                                     
no                0.172071   2313 -0.097897  0.637375
yes               0.338151   3321  0.068183  1.252560



paymentmethod


mean  count      diff      risk
paymentmethod                                                 
bank_transfer_(automatic)  0.168171   1219 -0.101797  0.622928
credit_card_(automatic)    0.164339   1217 -0.105630  0.608733
electronic_check           0.455890   1893  0.185922  1.688682
mailed_check               0.193870   1305 -0.076098  0.718121

## Feature Importance.
This is a method of scoring features to establish which features are important in developing the machine learning model. One method of scoring features is :
 ### 1. Mutual Information-
 It is the measure of the mutual dependence between two random variables. It can be implemented through scikit-learn.

In [43]:
from sklearn.metrics import mutual_info_score

In [44]:
for c in categorical:
    score = mutual_info_score(df_full_train.churn, df_full_train[c])
    print("Mutual Information for", c, "is",  score)

Mutual Information for gender is 0.0001174846211139946
Mutual Information for seniorcitizen is 0.009410216144208144
Mutual Information for partner is 0.009967689095399745
Mutual Information for dependents is 0.012345815445534689
Mutual Information for phoneservice is 0.00022871269738296285
Mutual Information for multiplelines is 0.0008574478744731856
Mutual Information for internetservice is 0.055867945893496467
Mutual Information for onlinesecurity is 0.06308524972985574
Mutual Information for onlinebackup is 0.0469234640537918
Mutual Information for deviceprotection is 0.04345286925268559
Mutual Information for techsupport is 0.06103245991777444
Mutual Information for streamingtv is 0.03185333110086085
Mutual Information for streamingmovies is 0.03158089669519908
Mutual Information for contract is 0.0983203874041556
Mutual Information for paperlessbilling is 0.01758882715925275
Mutual Information for paymentmethod is 0.043210027531582915


In [45]:
# We can also do this with the apply method
def mutual_info_score_churn(series):
    return mutual_info_score(series, df_full_train.churn)

In [46]:
mi = df_full_train[categorical].apply(mutual_info_score_churn)
mi.sort_values(ascending= False)

contract            0.098320
onlinesecurity      0.063085
techsupport         0.061032
internetservice     0.055868
onlinebackup        0.046923
deviceprotection    0.043453
paymentmethod       0.043210
streamingtv         0.031853
streamingmovies     0.031581
paperlessbilling    0.017589
dependents          0.012346
partner             0.009968
seniorcitizen       0.009410
multiplelines       0.000857
phoneservice        0.000229
gender              0.000117
dtype: float64

### 2. Correlation
While MI will be good for categorical features, correlation works for numerical features.

In [47]:
correlation = df_full_train[numerical].corrwith(df_full_train.churn)
correlation

tenure           -0.351885
monthlycharges    0.196805
totalcharges     -0.196353
dtype: float64

### One hot encoding using scikit learn

In [48]:
from sklearn.feature_extraction import DictVectorizer

In [49]:
data = df[['gender', 'contract']].head(10).to_dict(orient="records")
data

[{'gender': 'female', 'contract': 'month-to-month'},
 {'gender': 'male', 'contract': 'one_year'},
 {'gender': 'male', 'contract': 'month-to-month'},
 {'gender': 'male', 'contract': 'one_year'},
 {'gender': 'female', 'contract': 'month-to-month'},
 {'gender': 'female', 'contract': 'month-to-month'},
 {'gender': 'male', 'contract': 'month-to-month'},
 {'gender': 'female', 'contract': 'month-to-month'},
 {'gender': 'female', 'contract': 'month-to-month'},
 {'gender': 'male', 'contract': 'one_year'}]

In [50]:
dv = DictVectorizer(sparse= False)
dv.fit(data)

DictVectorizer(sparse=False)

In [51]:
dv.transform(data)

array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 0., 1.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [52]:
dv.get_feature_names_out()

array(['contract=month-to-month', 'contract=one_year', 'gender=female',
       'gender=male'], dtype=object)

In [53]:
train_dicts = df_train[categorical + numerical].to_dict(orient = "records")
dv = DictVectorizer(sparse= False)

In [54]:
X_train = dv.fit_transform(train_dicts)
X_train

array([[0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        7.20000e+01, 8.42515e+03],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+01, 1.02155e+03],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        5.00000e+00, 4.13650e+02],
       ...,
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        2.00000e+00, 1.90050e+02],
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        2.70000e+01, 7.61950e+02],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        9.00000e+00, 7.51650e+02]])

In [55]:
val_dicts = df_val[categorical + numerical].to_dict(orient = "records")
X_val = dv.transform(val_dicts)
X_val

array([[0.0000e+00, 0.0000e+00, 1.0000e+00, ..., 1.0000e+00, 7.1000e+01,
        4.9734e+03],
       [1.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 1.0000e+00,
        2.0750e+01],
       [1.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 1.0000e+00,
        2.0350e+01],
       ...,
       [1.0000e+00, 0.0000e+00, 0.0000e+00, ..., 1.0000e+00, 1.8000e+01,
        1.0581e+03],
       [1.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 1.0000e+00,
        9.3300e+01],
       [1.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 3.0000e+00,
        2.9285e+02]])

### Logistic regression for classification
g(x) = sigmoid(w0 + w1 * X)

In [56]:
from sklearn.linear_model import LogisticRegression

In [57]:
model = LogisticRegression()

In [58]:
model.fit(X_train, y_train)

/home/codespace/.local/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [59]:
model.coef_.round(2)

array([[ 0.48, -0.17, -0.41, -0.03, -0.08,  0.06, -0.09, -0.08, -0.03,
        -0.07, -0.34,  0.32, -0.09,  0.  , -0.26,  0.14,  0.01,  0.06,
        -0.09, -0.08,  0.27, -0.09, -0.28, -0.23,  0.12, -0.17,  0.06,
        -0.09, -0.03,  0.07, -0.06,  0.14, -0.25,  0.22, -0.12, -0.09,
         0.1 , -0.07, -0.09,  0.05,  0.21, -0.09, -0.23, -0.07,  0.  ]])

In [60]:
model.intercept_

array([-0.10904072])

In [61]:
y_pred = model.predict(X_val)
y_pred

array([0, 0, 0, ..., 0, 1, 1])

In [62]:
churn_decision = model.predict_proba(X_val)[:, 1] > 0.5
churn_decision

array([False, False, False, ..., False,  True,  True])

In [63]:
accuracy = (y_val == y_pred).mean()
accuracy

np.float64(0.8034066713981547)

In [64]:
dict_full_train = df_full_train [categorical + numerical].to_dict(orient = "records")
dict_full_train

[{'gender': 'male',
  'seniorcitizen': 0,
  'partner': 'yes',
  'dependents': 'yes',
  'phoneservice': 'yes',
  'multiplelines': 'no',
  'internetservice': 'no',
  'onlinesecurity': 'no_internet_service',
  'onlinebackup': 'no_internet_service',
  'deviceprotection': 'no_internet_service',
  'techsupport': 'no_internet_service',
  'streamingtv': 'no_internet_service',
  'streamingmovies': 'no_internet_service',
  'contract': 'two_year',
  'paperlessbilling': 'no',
  'paymentmethod': 'mailed_check',
  'tenure': 12,
  'monthlycharges': 19.7,
  'totalcharges': 258.35},
 {'gender': 'female',
  'seniorcitizen': 0,
  'partner': 'no',
  'dependents': 'no',
  'phoneservice': 'yes',
  'multiplelines': 'no',
  'internetservice': 'dsl',
  'onlinesecurity': 'yes',
  'onlinebackup': 'yes',
  'deviceprotection': 'yes',
  'techsupport': 'yes',
  'streamingtv': 'no',
  'streamingmovies': 'yes',
  'contract': 'one_year',
  'paperlessbilling': 'no',
  'paymentmethod': 'credit_card_(automatic)',
  'tenur

In [65]:
dv.fit(dict_full_train)

DictVectorizer(sparse=False)

In [66]:
X_full_train = dv.transform(dict_full_train)
X_full_train

array([[0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        1.20000e+01, 2.58350e+02],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        4.20000e+01, 3.16055e+03],
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        7.10000e+01, 4.68175e+03],
       ...,
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.80000e+01, 2.97950e+03],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.00000e+00, 1.14100e+02],
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        1.60000e+01, 1.11485e+03]])

In [67]:
df_full_train

customerid  gender  seniorcitizen partner dependents  tenure  \
1814  5442-pptjy    male              0     yes        yes      12   
5946  6261-rcvns  female              0      no         no      42   
3881  2176-osjuv    male              0     yes         no      71   
2389  6161-erdgd    male              0     yes        yes      71   
3676  2364-ufrom    male              0      no         no      30   
...          ...     ...            ...     ...        ...     ...   
905   0781-lkxbr    male              1      no         no       9   
5192  3507-gasnp    male              0      no        yes      60   
3980  8868-wozgu    male              0      no         no      28   
235   1251-krreg    male              0      no         no       2   
5157  5840-nvdcg  female              0     yes        yes      16   

     phoneservice multiplelines internetservice       onlinesecurity  ...  \
1814          yes            no              no  no_internet_service  ...   
5946          yes            no             dsl                  yes  ...   
3881          yes           yes             dsl                  yes  ...   
2389          yes           yes             dsl                  yes  ...   
3676          yes            no             dsl                  yes  ...   
...           ...           ...             ...                  ...  ...   
905           yes           yes     fiber_optic                   no  ...   
5192          yes            no              no  no_internet_service  ...   
3980          yes           yes     fiber_optic                   no  ...   
235           yes           yes             dsl                   no  ...   
5157          yes            no             dsl                  yes  ...   

         deviceprotection          techsupport          streamingtv  \
1814  no_internet_service  no_internet_service  no_internet_service   
5946                  yes                  yes                   no   
3881                   no                  yes                   no   
2389                  yes                  yes                  yes   
3676                   no                  yes                  yes   
...                   ...                  ...                  ...   
905                   yes                   no                  yes   
5192  no_internet_service  no_internet_service  no_internet_service   
3980                  yes                   no                  yes   
235                    no                   no                   no   
5157                   no                  yes                   no   

          streamingmovies        contract paperlessbilling  \
1814  no_internet_service        two_year               no   
5946                  yes        one_year               no   
3881                   no        two_year               no   
2389                  yes        one_year               no   
3676                   no        one_year               no   
...                   ...             ...              ...   
905                   yes  month-to-month              yes   
5192  no_internet_service        two_year               no   
3980                  yes  month-to-month              yes   
235                    no  month-to-month              yes   
5157                  yes        two_year               no   

                  paymentmethod monthlycharges  totalcharges  churn  
1814               mailed_check          19.70        258.35      0  
5946    credit_card_(automatic)          73.90       3160.55      1  
3881  bank_transfer_(automatic)          65.15       4681.75      0  
2389           electronic_check          85.45       6300.85      0  
3676           electronic_check          70.40       2044.75      0  
...                         ...            ...           ...    ...  
905            electronic_check         100.50        918.60      1  
5192               mailed_check          19.95       1189.90      0  
3980        

In [68]:
y_full_train = df_full_train.churn.values
y_full_train

array([0, 1, 0, ..., 1, 1, 0])

In [69]:
model = LogisticRegression()

In [70]:
model.fit(X_full_train, y_full_train)

/home/codespace/.local/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [71]:
df_test

customerid  gender  seniorcitizen partner dependents  tenure  \
0     8879-zkjof  female              0      no         no      41   
1     0201-mibol  female              1      no         no      66   
2     1600-dilpe  female              0      no         no      12   
3     8601-qacrs  female              0      no         no       5   
4     7919-zodzz  female              0     yes        yes      10   
...          ...     ...            ...     ...        ...     ...   
1404  5130-iekqt    male              1      no         no      25   
1405  4452-rohmo  female              0      no         no      15   
1406  6164-haqtx    male              0      no         no      71   
1407  3982-dqlus    male              1     yes        yes      65   
1408  9874-qlclh  female              0     yes        yes      17   

     phoneservice     multiplelines internetservice       onlinesecurity  \
0             yes                no             dsl                  yes   
1             yes               yes     fiber_optic                  yes   
2             yes                no             dsl                   no   
3             yes               yes             dsl                   no   
4             yes                no             dsl                   no   
...           ...               ...             ...                  ...   
1404          yes               yes     fiber_optic                   no   
1405          yes                no              no  no_internet_service   
1406           no  no_phone_service             dsl                  yes   
1407          yes               yes     fiber_optic                  yes   
1408          yes               yes     fiber_optic                  yes   

             onlinebackup     deviceprotection          techsupport  \
0                      no                  yes                  yes   
1                      no                   no                   no   
2                      no                   no                   no   
3                      no                   no                   no   
4                     yes                  yes                   no   
...                   ...                  ...                  ...   
1404                  yes                  yes                   no   
1405  no_internet_service  no_internet_service  no_internet_service   
1406                  yes                  yes                  yes   
1407                  yes                   no                   no   
1408                   no                  yes                   no   

              streamingtv      streamingmovies        contract  \
0                     yes                  yes        one_year   
1                     yes                  yes        two_year   
2                      no                   no  month-to-month   
3                      no                   no  month-to-month   
4                      no                  yes        one_year   
...                   ...                  ...             ...   
1404                  yes                  yes  month-to-month   
1405  no_internet_service  no_internet_service        two_year   
1406                  yes                   no        two_year   
1407                   no                   no  month-to-month   
1408                  yes                  yes  month-to-month   

     paperlessbilling              paymentmethod  monthlycharges  totalcharges  
0                 yes  bank_transfer_(automatic)           79.85       3320.75  
1                 yes  bank_transfer_(automatic)          102.40       6471.85  
2                 yes  bank_transfer_(automatic)           45.00        524.35  
3                 yes               mailed_check           50.60        249.95  
4                 yes               mailed_check           65.90        660.05  
...               ...                        ...             ...           ...  
1404               no               mai

In [78]:
test_dicts = df_test[categorical + numerical].to_dict(orient = "records")


In [73]:
X_test = dv.transform(test_dicts)
X_test

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        4.10000e+01, 3.32075e+03],
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        6.60000e+01, 6.47185e+03],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.20000e+01, 5.24350e+02],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        7.10000e+01, 3.88865e+03],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        6.50000e+01, 5.68845e+03],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.70000e+01, 1.74350e+03]])

In [74]:
y_pred = model.predict(X_test)

In [75]:
(y_pred == y_test).mean()

np.float64(0.8119233498935415)