In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df= pd.read_csv("laptops.csv")
df

Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RAM  Storage Storage type       GPU  \
0     ExpertBook      Intel Core i5    8      512          SSD       NaN   
1             Go      Intel Celeron    8      256          SSD       NaN   
2     ExpertBook      Intel Core i3    8      256          SSD       NaN   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2159        Book  Intel Evo Core i7   16      256          SSD       NaN   

      Screen Touch  Final Price  
0       15.6    No      1009.00  
1       15.6    No       299.00  
2       15.6    No       789.00  
3       15.6    No      1199.00  
4       15.6    No       669.01  
...      ...   ...          ...  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  
2159    13.4   Yes      1699.99  

[2160 rows x 12 columns]

In [3]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [4]:
df.columns= df.columns.str.replace(' ', "_").str.lower()
df

laptop       status   brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           model                cpu  ram  storage storage_type       gpu  \
0     ExpertBook      Intel Core i5    8      512          SSD       NaN   
1             Go      Intel Celeron    8      256          SSD       NaN   
2     ExpertBook      Intel Core i3    8      256          SSD       NaN   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2159        Book  Intel Evo Core i7   16      256          SSD       NaN   

      screen touch  final_price  
0       15.6    No      1009.00  
1       15.6    No       299.00  
2       15.6    No       789.00  
3       15.6    No      1199.00  
4       15.6    No       669.01  
...      ...   ...          ...  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  
2159    13.4   Yes      1699.99  

[2160 rows x 12 columns]

In [24]:
df1 = df[['ram','storage','screen','final_price']]
df1

ram  storage  screen  final_price
0       8      512    15.6      1009.00
1       8      256    15.6       299.00
2       8      256    15.6       789.00
3      16     1000    15.6      1199.00
4      16      512    15.6       669.01
...   ...      ...     ...          ...
2155   16     1000    17.3      2699.99
2156   16     1000    17.3      2899.99
2157   32     1000    17.3      3399.99
2158   16     1000    13.4      1899.99
2159   16      256    13.4      1699.99

[2160 rows x 4 columns]

In [25]:
df1.isnull().sum()

ram            0
storage        0
screen         4
final_price    0
dtype: int64

In [26]:
df1.screen.mean()

np.float64(15.168112244897959)

In [27]:
df1.screen = df1.screen.fillna(15.17)

/tmp/ipykernel_2683/536575639.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1.screen = df1.screen.fillna(15.17)


In [28]:
df1.isnull().sum()

ram            0
storage        0
screen         0
final_price    0
dtype: int64

In [29]:
df1.dtypes

ram              int64
storage          int64
screen         float64
final_price    float64
dtype: object

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
df_full_train, df_test = train_test_split(df1, random_state= 42, test_size= 0.2)

In [32]:
df_train, df_val = train_test_split(df_full_train, random_state= 42, test_size= .25)

In [33]:
y_train = df_train.final_price.values
y_train

array([1299.  , 2243.18, 2749.  , ..., 1999.  , 1199.  ,  779.  ])

In [34]:
len(df_train), len(df_val), len(df_test)

(1296, 432, 432)

In [35]:
del df_train["final_price"]

In [36]:
df_train

ram  storage  screen
1781   16     1000    15.6
2024   32     1000    17.3
2109   32     1000    17.3
33      8      256    15.6
1720   16      512    15.6
...   ...      ...     ...
216     8      256    15.6
1976   16      512    14.0
183    32     1000    16.0
1696   16      512    15.6
61      8      512    15.6

[1296 rows x 3 columns]

In [37]:
y_val =  df_val.final_price.values
del df_val["final_price"]
df_val

ram  storage  screen
982    32     1000    17.0
1015    8      256    14.0
10      8      256    15.6
2123   32     1000    13.4
116    16      512    15.6
...   ...      ...     ...
1910   16      512    16.1
1938    8      256    15.6
491    32     1000    16.0
1458   16      512    16.1
341     8      512    13.3

[432 rows x 3 columns]

In [38]:
y_test =  df_test.final_price.values
del df_test["final_price"]
df_test

ram  storage  screen
2079   32     1000    15.6
668     4       64    14.1
2073   32     1000    14.0
1113   16      512    13.3
788    32     1000    16.0
...   ...      ...     ...
438    32     1000    17.3
900     8      512    15.6
1613    8      256    15.6
20     16     1000    15.6
785     8      512    15.0

[432 rows x 3 columns]

In [39]:
from sklearn.preprocessing import StandardScaler

In [40]:
X_unscaled = df_train.values
X_unscaled

array([[  16. , 1000. ,   15.6],
       [  32. , 1000. ,   17.3],
       [  32. , 1000. ,   17.3],
       ...,
       [  32. , 1000. ,   16. ],
       [  16. ,  512. ,   15.6],
       [   8. ,  512. ,   15.6]])

In [41]:
scaler = StandardScaler()

In [42]:
X_train_scaled = scaler.fit_transform(X_unscaled)
X_train_scaled

array([[ 0.04565877,  1.11543519,  0.34711547],
       [ 1.66685769,  1.11543519,  1.74775794],
       [ 1.66685769,  1.11543519,  1.74775794],
       ...,
       [ 1.66685769,  1.11543519,  0.6766784 ],
       [ 0.04565877, -0.24190812,  0.34711547],
       [-0.7649407 , -0.24190812,  0.34711547]])

In [43]:
len(X_train_scaled)

1296

In [44]:
y_train_transformed = np.log1p(y_train)
y_train_transformed

array([7.17011954, 7.71609548, 7.91935619, ..., 7.60090246, 7.09007684,
       6.65929392])

In [45]:
from sklearn.linear_model import LinearRegression

In [46]:
model= LinearRegression()

In [47]:
model.fit(X_train_scaled, y_train_transformed)

LinearRegression()

In [48]:
X_val_unscaled = df_val.values
X_val_scaled = scaler.transform(X_val_unscaled)
X_val_scaled

array([[ 1.66685769,  1.11543519,  1.50058574],
       [-0.7649407 , -0.95395707, -0.97113627],
       [-0.7649407 , -0.95395707,  0.34711547],
       ...,
       [ 1.66685769,  1.11543519,  0.6766784 ],
       [ 0.04565877, -0.24190812,  0.75906913],
       [-0.7649407 , -0.24190812, -1.5478714 ]])

In [50]:
y_val_transformed = np.log1p(y_val)

In [51]:
y_pred = model.predict(X_val_scaled)

In [57]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, root_mean_squared_error

In [54]:
mae = mean_absolute_error(y_val_transformed, y_pred)
mae

np.float64(0.3421478290200775)

In [55]:
mse= mean_squared_error(y_val_transformed, y_pred)
mse

np.float64(0.18551039879483439)

In [58]:
rmse = root_mean_squared_error(y_val_transformed, y_pred)
rmse

np.float64(0.4307091812288593)

In [59]:
model.score(X_train_scaled, y_train_transformed)

0.5648802628326233

In [60]:
model.score(X_val_scaled, y_val_transformed)

0.5224933899906234

In [61]:
from sklearn.linear_model import Ridge

In [63]:
ridgeReg = Ridge(alpha= 0.01)

In [64]:
ridgeReg.fit(X_train_scaled, y_train_transformed)

Ridge(alpha=0.01)

In [65]:
y_ridge_pred = ridgeReg.predict(X_val_scaled)

In [67]:
root_mean_squared_error(y_ridge_pred, y_val_transformed)

np.float64(0.4307091512883323)

In [68]:
ridgeReg = Ridge(alpha= 0.1)
ridgeReg.fit(X_train_scaled, y_train_transformed)
y_ridge_pred = ridgeReg.predict(X_val_scaled)
root_mean_squared_error(y_ridge_pred, y_val_transformed)

np.float64(0.4307088825815851)

In [69]:
ridgeReg = Ridge(alpha= 1)
ridgeReg.fit(X_train_scaled, y_train_transformed)
y_ridge_pred = ridgeReg.predict(X_val_scaled)
root_mean_squared_error(y_ridge_pred, y_val_transformed)

np.float64(0.43070627041775933)

In [70]:
ridgeReg = Ridge(alpha= 10)
ridgeReg.fit(X_train_scaled, y_train_transformed)
y_ridge_pred = ridgeReg.predict(X_val_scaled)
root_mean_squared_error(y_ridge_pred, y_val_transformed)

np.float64(0.4306875038552714)

In [71]:
ridgeReg = Ridge(alpha= 100)
ridgeReg.fit(X_train_scaled, y_train_transformed)
y_ridge_pred = ridgeReg.predict(X_val_scaled)
root_mean_squared_error(y_ridge_pred, y_val_transformed)

np.float64(0.4311208650444837)

In [72]:
ridgeReg = Ridge(alpha= 1)
ridgeReg.fit(X_train_scaled, y_train_transformed)
y_ridge_pred = ridgeReg.predict(X_val_scaled)
ridgeReg.score(X_train_scaled, y_train_transformed)

0.5648800960092626