# NUMPY- Numerical Python

In [2]:
import numpy as np

## Creating  1D arrays

In [3]:
# Zero arrays
print(np.zeros(6))

#Array of 1s
print(np.ones(6))

#Array with arbiturary numbers
# np.full(size, number)
print(np.full(6, 2.5))

[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[2.5 2.5 2.5 2.5 2.5 2.5]


In [4]:
# Creating arrays from python list
ls = [1, 2, 3, 4, 5]
a= np.array(ls)
a

array([1, 2, 3, 4, 5])

In [5]:
# Creating an array from a range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# Indicating the start of the range.
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [7]:
# Creating an array of equal numbers from 0 to 1
np.linspace(0, 1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [8]:
# If we want 10 items in this array
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Creating Multidimensional arrays

In [9]:
# Creating a zero array with 5 rows and 2 columns. Notice the (())
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
# Creating 2D arrays from python lists
ls1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
n= np.array(ls1)
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
## Accessing contents of the array
# Second row
n[1]

array([4, 5, 6])

In [12]:
# Second item in first row
n[0, 1]

np.int64(2)

In [13]:
# or
n[0][1]

np.int64(2)

In [14]:
# We can change values
n[0,1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [15]:
# Getting the columns
n[:, 1]

array([20,  5,  8])

In [16]:
# We can also change column values
n[:, 2] = [5, 10, 15]
n

array([[ 1, 20,  5],
       [ 4,  5, 10],
       [ 7,  8, 15]])

## Randomly generated arrays

In [17]:
# A random uniform distribution of 5 rows and 2 columns
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [18]:
# Sample numbers from normal distribution
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [19]:
# Generate random integers from 0-100 (100 is exclusive) and with size 5 by 2
np.random.seed(2)
np.random.randint(0, 100, size= (5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [20]:
# Generate random floats between 0 and 1
np.random.seed(2)
np.random.random((5,2))

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [21]:
np.random.seed(2)
np.random.normal(size=(5,2))

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

## Element wise operations

In [22]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [23]:
## Addition
b + 5

array([5, 6, 7, 8, 9])

In [24]:
## Subtraction
b - 4

array([-4, -3, -2, -1,  0])

In [25]:
## Multiplication 
b * 2

array([0, 2, 4, 6, 8])

In [26]:
## Division
b/3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333])

In [27]:
## Power
b ** 3

array([ 0,  1,  8, 27, 64])

In [28]:
b // 2

array([0, 0, 1, 1, 2])

In [29]:
b % 2

array([0, 1, 0, 1, 0])

In [30]:
## Adding two arrays
a+b

array([1, 3, 5, 7, 9])

## Comparison operators

In [31]:
b >=2

array([False, False,  True,  True,  True])

In [32]:
a == b

array([False, False, False, False, False])

In [33]:
a > b

array([ True,  True,  True,  True,  True])

In [34]:
b > a

array([False, False, False, False, False])

In [35]:
b != a

array([ True,  True,  True,  True,  True])

In [36]:
b [b >=2]

array([2, 3, 4])

## Summarizing operations

In [37]:
b.min()

np.int64(0)

In [38]:
a.max()

np.int64(5)

In [39]:
a.sum()

np.int64(15)

In [40]:
b.mean()

np.float64(2.0)

In [41]:
a.cumsum()

array([ 1,  3,  6, 10, 15])

In [42]:
b.std()

np.float64(1.4142135623730951)

In [43]:
# Mean of each column
n.mean(axis= 0)

array([ 4., 11., 10.])

In [44]:
n

array([[ 1, 20,  5],
       [ 4,  5, 10],
       [ 7,  8, 15]])

In [45]:
n.mean(axis=1)

array([ 8.66666667,  6.33333333, 10.        ])

## Arithmetic operations

In [46]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [47]:
np.log(n)

array([[0.        , 2.99573227, 1.60943791],
       [1.38629436, 1.60943791, 2.30258509],
       [1.94591015, 2.07944154, 2.7080502 ]])

In [48]:
np.exp(n)

array([[2.71828183e+00, 4.85165195e+08, 1.48413159e+02],
       [5.45981500e+01, 1.48413159e+02, 2.20264658e+04],
       [1.09663316e+03, 2.98095799e+03, 3.26901737e+06]])

# LINEAR ALGEBRA REFRESHER

## Scalar multiplication

In [49]:
a = np.array([2, 5, 8, 12])
3 * a

array([ 6, 15, 24, 36])

## Vector-vector multiplication also scalar or dot product. This is different from element-wise multiplication. This produces a single number.

In [51]:
a = np.array([2, 4, 6, 8])
b = np.array([1, 0, 0, 2])

In [53]:
# Element-wise multiplication
a * b

array([ 2,  0,  0, 16])

In [77]:
# Defining a function
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [78]:
vector_vector_multiplication(a, b)

np.float64(18.0)

In [79]:
# Scalar/ dot multiplication using numpy method
np.dot(a, b)

np.int64(18)

## Matrix-vector multiplication

In [81]:
U = np.array([[2, 4, 5, 6], [1, 2, 1, 2], [3, 1, 2, 1]])
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [74]:
v = np.array([1, 0.5, 2, 1])
v

array([1. , 0.5, 2. , 1. ])

In [80]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [82]:
matrix_vector_multiplication(U, v)

array([20. ,  6. ,  8.5])

In [83]:
# Numpy dot method
np.dot(u, v)

array([20. ,  6. ,  8.5])

## Matrix-matrix multiplication

In [65]:
U = np.array([[2, 4, 5, 6], [1, 2, 1, 2], [3, 1, 2, 1]])
V = np.array([[1, 1, 2], [0, 0.5, 1], [0, 2, 1], [2, 1, 0]])

In [84]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [85]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [66]:
np.dot(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity matrix


In [67]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## Matrix inverse

In [68]:
Vs = V [[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [69]:
Vinv = np.linalg.inv(Vs)
Vinv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [70]:
np.dot(Vinv, Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# PANDAS

In [2]:
import pandas as pd

In [3]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]
 
columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [4]:
df = pd.DataFrame(data= data, columns= columns)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

## Adding columns to DataFrames

In [5]:
df['id'] = [1, 2, 3, 4, 5]
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  id  
0         sedan   2000   1  
1         Sedan  27150   2  
2   convertible  54990   3  
3       4dr SUV  34450   4  
4        Pickup  32340   5

## Deleting columns from DataFrames

In [6]:
del df["id"]
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

## Extraction
By leveraging the power of Pandas Series, you can easily extract, transform, and analyze specific columns or subsets of data from a DataFrame, making it a versatile tool for data manipulation and analysis in Python.

In [7]:
# To access one serie you can use the dot notation...
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

In [8]:
# ... or the bracket notation 
df['Make']

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: object

## Index
The numbers in the first column refer to each row (called Index).

In [9]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [10]:
# We can change the index
df.index = ["a", 'b', 'c', 'd', 'e']

In [11]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a   Nissan    Stanza  1991      138.0                 4            MANUAL   
b  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus     Elise  2010      218.0                 4            MANUAL   
d      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
e   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
a         sedan   2000  
b         Sedan  27150  
c   convertible  54990  
d       4dr SUV  34450  
e        Pickup  32340

In [13]:
# We can remove the new index
df.reset_index()

index     Make     Model  Year  Engine HP  Engine Cylinders  \
0     a   Nissan    Stanza  1991      138.0                 4   
1     b  Hyundai    Sonata  2017        NaN                 4   
2     c    Lotus     Elise  2010      218.0                 4   
3     d      GMC    Acadia  2017      194.0                 4   
4     e   Nissan  Frontier  2017      261.0                 6   

  Transmission Type Vehicle_Style   MSRP  
0            MANUAL         sedan   2000  
1         AUTOMATIC         Sedan  27150  
2            MANUAL   convertible  54990  
3         AUTOMATIC       4dr SUV  34450  
4            MANUAL        Pickup  32340

In [14]:
# we can remove the index column
df.reset_index(drop= True)

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

## Accessing elements using loc and iloc

In [15]:
df.index = ["a", 'b', 'c', 'd', 'e']

In [20]:
# Returns a series
df.loc["a"]

Make                 Nissan
Model                Stanza
Year                   1991
Engine HP             138.0
Engine Cylinders          4
Transmission Type    MANUAL
Vehicle_Style         sedan
MSRP                   2000
Name: a, dtype: object

In [21]:
# returns it as a dataframe
df.loc[["a"]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a  Nissan  Stanza  1991      138.0                 4            MANUAL   

  Vehicle_Style  MSRP  
a         sedan  2000

In [17]:
df.loc[["a", "c"]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a  Nissan  Stanza  1991      138.0                 4            MANUAL   
c   Lotus   Elise  2010      218.0                 4            MANUAL   

  Vehicle_Style   MSRP  
a         sedan   2000  
c   convertible  54990

In [22]:
df.iloc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: b, dtype: object

In [23]:
df.iloc[[1]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
b  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   

  Vehicle_Style   MSRP  
b         Sedan  27150

In [24]:
df.iloc[[1, 3]]

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
b  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   
d      GMC  Acadia  2017      194.0                 4         AUTOMATIC   

  Vehicle_Style   MSRP  
b         Sedan  27150  
d       4dr SUV  34450

## Element-wise operations

In [25]:
df['Engine HP'] / 100

a    1.38
b     NaN
c    2.18
d    1.94
e    2.61
Name: Engine HP, dtype: float64

## Filtering-
Filtering refers to selecting specific rows or columns from a DataFrame based on certain conditions. 
One common technique is **to use boolean indexing**. This involves creating a boolean mask that specifies the conditions we want to apply to our data. The mask is a DataFrame or Series of the same shape as the original data, where each element is either True or False depending on whether the corresponding element in the original data satisfies the condition.

In [26]:
df[df.Year >= 2015]

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
b  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
d      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
e   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
b         Sedan  27150  
d       4dr SUV  34450  
e        Pickup  32340

Another useful technique for filtering is using the **.query() method**. This method allows us to filter rows based on a string expression, similar to writing SQL queries. 

In [28]:
filtered_df = df.query('Year >=  2015')
filtered_df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
b  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
d      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
e   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
b         Sedan  27150  
d       4dr SUV  34450  
e        Pickup  32340

It is also possible to combine several condition, for example, you want to have all Nissans after the year 2015.

In [29]:
df[(df.Make == 'Nissan') & (df.Year > 2015)]

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
e  Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
e        Pickup  32340

## String operations
This is something NumPy doesn’t have, because NumPy is mostly used for processing numbers. In Pandas we often have to deal with strings.

In [30]:
df['Vehicle_Style'].str.lower()

a          sedan
b          sedan
c    convertible
d        4dr suv
e         pickup
Name: Vehicle_Style, dtype: object

In [31]:
df['Vehicle_Style'].str.replace(' ','_')

a          sedan
b          Sedan
c    convertible
d        4dr_SUV
e         Pickup
Name: Vehicle_Style, dtype: object

In [32]:
# Both operations can be chained
df['Vehicle_Style'] = df['Vehicle_Style'].str.lower().str.replace(' ','_')
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
a   Nissan    Stanza  1991      138.0                 4            MANUAL   
b  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
c    Lotus     Elise  2010      218.0                 4            MANUAL   
d      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
e   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
a         sedan   2000  
b         sedan  27150  
c   convertible  54990  
d       4dr_suv  34450  
e        pickup  32340

## Summarizing operations

In [33]:
df.MSRP.min()

np.int64(2000)

In [34]:
df.MSRP.mean()

np.float64(30186.0)

In [35]:
df.MSRP.describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

In [36]:
df.describe().round(2)

Year  Engine HP  Engine Cylinders      MSRP
count     5.00       4.00              5.00      5.00
mean   2010.40     202.75              4.40  30186.00
std      11.26      51.30              0.89  18985.04
min    1991.00     138.00              4.00   2000.00
25%    2010.00     180.00              4.00  27150.00
50%    2017.00     206.00              4.00  32340.00
75%    2017.00     228.75              4.00  34450.00
max    2017.00     261.00              6.00  54990.00

## Categorical Columns
There are also some functions for string values. The next function can be used for numerical values, too. Nunique() returns the number of unique values. You can apply this on single columns or DataFrames.

In [37]:
df.Make.nunique()

4

In [38]:
df.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Engine Cylinders     2
Transmission Type    2
Vehicle_Style        4
MSRP                 5
dtype: int64

In [39]:
df.Year.unique()

array([1991, 2017, 2010])

In [40]:
df.Make.unique()

array(['Nissan', 'Hyundai', 'Lotus', 'GMC'], dtype=object)

## Missing values

In [41]:
df.isnull()

Make  Model   Year  Engine HP  Engine Cylinders  Transmission Type  \
a  False  False  False      False             False              False   
b  False  False  False       True             False              False   
c  False  False  False      False             False              False   
d  False  False  False      False             False              False   
e  False  False  False      False             False              False   

   Vehicle_Style   MSRP  
a          False  False  
b          False  False  
c          False  False  
d          False  False  
e          False  False

In [42]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

In [43]:
df.groupby("Transmission Type").MSRP.mean()

Transmission Type
AUTOMATIC    30800.000000
MANUAL       29776.666667
Name: MSRP, dtype: float64

## Getting Numpy arrays

In [44]:
df.Make.values

array(['Nissan', 'Hyundai', 'Lotus', 'GMC', 'Nissan'], dtype=object)

In [45]:
df.values

array([['Nissan', 'Stanza', 1991, 138.0, 4, 'MANUAL', 'sedan', 2000],
       ['Hyundai', 'Sonata', 2017, nan, 4, 'AUTOMATIC', 'sedan', 27150],
       ['Lotus', 'Elise', 2010, 218.0, 4, 'MANUAL', 'convertible', 54990],
       ['GMC', 'Acadia', 2017, 194.0, 4, 'AUTOMATIC', '4dr_suv', 34450],
       ['Nissan', 'Frontier', 2017, 261.0, 6, 'MANUAL', 'pickup', 32340]],
      dtype=object)

In [46]:
df.to_dict(orient= "records")

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'sedan',
  'MSRP': 27150},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr_suv',
  'MSRP': 34450},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'pickup',
  'MSRP': 32340}]

In [47]:
df.to_dict()

{'Make': {'a': 'Nissan',
  'b': 'Hyundai',
  'c': 'Lotus',
  'd': 'GMC',
  'e': 'Nissan'},
 'Model': {'a': 'Stanza',
  'b': 'Sonata',
  'c': 'Elise',
  'd': 'Acadia',
  'e': 'Frontier'},
 'Year': {'a': 1991, 'b': 2017, 'c': 2010, 'd': 2017, 'e': 2017},
 'Engine HP': {'a': 138.0, 'b': nan, 'c': 218.0, 'd': 194.0, 'e': 261.0},
 'Engine Cylinders': {'a': 4, 'b': 4, 'c': 4, 'd': 4, 'e': 6},
 'Transmission Type': {'a': 'MANUAL',
  'b': 'AUTOMATIC',
  'c': 'MANUAL',
  'd': 'AUTOMATIC',
  'e': 'MANUAL'},
 'Vehicle_Style': {'a': 'sedan',
  'b': 'sedan',
  'c': 'convertible',
  'd': '4dr_suv',
  'e': 'pickup'},
 'MSRP': {'a': 2000, 'b': 27150, 'c': 54990, 'd': 34450, 'e': 32340}}