In [1]:
import numpy as np

## Creating  1D arrays

In [13]:
# Zero arrays
print(np.zeros(6))

#Array of 1s
print(np.ones(6))

#Array with arbiturary numbers
# np.full(size, number)
print(np.full(6, 2.5))

[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[2.5 2.5 2.5 2.5 2.5 2.5]


In [15]:
# Creating arrays from python list
ls = [1, 2, 3, 4, 5]
a= np.array(ls)
a

array([1, 2, 3, 4, 5])

In [16]:
# Creating an array from a range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# Indicating the start of the range.
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [18]:
# Creating an array of equal numbers from 0 to 1
np.linspace(0, 1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [19]:
# If we want 10 items in this array
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Creating Multidimensional arrays

In [22]:
# Creating a zero array with 5 rows and 2 columns. Notice the (())
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [24]:
# Creating 2D arrays from python lists
ls1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
n= np.array(ls1)
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
## Accessing contents of the array
# Second row
n[1]

array([4, 5, 6])

In [27]:
# Second item in first row
n[0, 1]

np.int64(2)

SyntaxError: invalid syntax (3780661915.py, line 1)