In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("new_bank.csv")
df

age           job   marital  education default  balance housing loan  \
0       58    management   married   tertiary      no     2143     yes   no   
1       44    technician    single  secondary      no       29     yes   no   
2       33  entrepreneur   married  secondary      no        2     yes  yes   
3       47   blue-collar   married    unknown      no     1506     yes   no   
4       33       unknown    single    unknown      no        1      no   no   
...    ...           ...       ...        ...     ...      ...     ...  ...   
45206   51    technician   married   tertiary      no      825      no   no   
45207   71       retired  divorced    primary      no     1729      no   no   
45208   72       retired   married  secondary      no     5715      no   no   
45209   57   blue-collar   married  secondary      no      668      no   no   
45210   37  entrepreneur   married  secondary      no     2971      no   no   

         contact  day month  duration  campaign  pdays  previous poutcome    y  
0        unknown    5   may       261         1     -1         0  unknown   no  
1        unknown    5   may       151         1     -1         0  unknown   no  
2        unknown    5   may        76         1     -1         0  unknown   no  
3        unknown    5   may        92         1     -1         0  unknown   no  
4        unknown    5   may       198         1     -1         0  unknown   no  
...          ...  ...   ...       ...       ...    ...       ...      ...  ...  
45206   cellular   17   nov       977         3     -1         0  unknown  yes  
45207   cellular   17   nov       456         2     -1         0  unknown  yes  
45208   cellular   17   nov      1127         5    184         3  success  yes  
45209  telephone   17   nov       508         4     -1         0  unknown   no  
45210   cellular   17   nov       361         2    188        11    other   no  

[45211 rows x 17 columns]

In [3]:
new_df = df[["age", "job", "marital", "education", "balance", "housing", "contact", "day", "month", "duration", "campaign","pdays",
"previous","poutcome","y"]]
new_df

age           job   marital  education  balance housing    contact  \
0       58    management   married   tertiary     2143     yes    unknown   
1       44    technician    single  secondary       29     yes    unknown   
2       33  entrepreneur   married  secondary        2     yes    unknown   
3       47   blue-collar   married    unknown     1506     yes    unknown   
4       33       unknown    single    unknown        1      no    unknown   
...    ...           ...       ...        ...      ...     ...        ...   
45206   51    technician   married   tertiary      825      no   cellular   
45207   71       retired  divorced    primary     1729      no   cellular   
45208   72       retired   married  secondary     5715      no   cellular   
45209   57   blue-collar   married  secondary      668      no  telephone   
45210   37  entrepreneur   married  secondary     2971      no   cellular   

       day month  duration  campaign  pdays  previous poutcome    y  
0        5   may       261         1     -1         0  unknown   no  
1        5   may       151         1     -1         0  unknown   no  
2        5   may        76         1     -1         0  unknown   no  
3        5   may        92         1     -1         0  unknown   no  
4        5   may       198         1     -1         0  unknown   no  
...    ...   ...       ...       ...    ...       ...      ...  ...  
45206   17   nov       977         3     -1         0  unknown  yes  
45207   17   nov       456         2     -1         0  unknown  yes  
45208   17   nov      1127         5    184         3  success  yes  
45209   17   nov       508         4     -1         0  unknown   no  
45210   17   nov       361         2    188        11    other   no  

[45211 rows x 15 columns]

In [4]:
new_df.isnull().sum()

age          0
job          0
marital      0
education    0
balance      0
housing      0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

## Question 1

In [5]:
new_df.education.value_counts()

education
secondary    23202
tertiary     13301
primary       6851
unknown       1857
Name: count, dtype: int64

## Question 2

In [6]:
numerical = new_df.dtypes[new_df.dtypes == "int64"]
numerical= numerical.index
numerical= list(numerical)
numerical = ['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous']
numerical

['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous']

In [7]:
num_df = new_df[numerical].corr()
num_df

age   balance       day  duration  campaign     pdays  previous
age       1.000000  0.097783 -0.009120 -0.004648  0.004760 -0.023758  0.001288
balance   0.097783  1.000000  0.004503  0.021560 -0.014578  0.003435  0.016674
day      -0.009120  0.004503  1.000000 -0.030206  0.162490 -0.093044 -0.051710
duration -0.004648  0.021560 -0.030206  1.000000 -0.084570 -0.001565  0.001203
campaign  0.004760 -0.014578  0.162490 -0.084570  1.000000 -0.088628 -0.032855
pdays    -0.023758  0.003435 -0.093044 -0.001565 -0.088628  1.000000  0.454820
previous  0.001288  0.016674 -0.051710  0.001203 -0.032855  0.454820  1.000000

In [8]:
new_df.y.value_counts()


y
no     39922
yes     5289
Name: count, dtype: int64

In [9]:
(new_df.y == "yes").astype("int")

0        0
1        0
2        0
3        0
4        0
        ..
45206    1
45207    1
45208    1
45209    0
45210    0
Name: y, Length: 45211, dtype: int64

In [10]:
new_df.y = (new_df.y == "yes").astype("int")
new_df.y

/tmp/ipykernel_3118/199439852.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df.y = (new_df.y == "yes").astype("int")


0        0
1        0
2        0
3        0
4        0
        ..
45206    1
45207    1
45208    1
45209    0
45210    0
Name: y, Length: 45211, dtype: int64

In [11]:
new_df

age           job   marital  education  balance housing    contact  \
0       58    management   married   tertiary     2143     yes    unknown   
1       44    technician    single  secondary       29     yes    unknown   
2       33  entrepreneur   married  secondary        2     yes    unknown   
3       47   blue-collar   married    unknown     1506     yes    unknown   
4       33       unknown    single    unknown        1      no    unknown   
...    ...           ...       ...        ...      ...     ...        ...   
45206   51    technician   married   tertiary      825      no   cellular   
45207   71       retired  divorced    primary     1729      no   cellular   
45208   72       retired   married  secondary     5715      no   cellular   
45209   57   blue-collar   married  secondary      668      no  telephone   
45210   37  entrepreneur   married  secondary     2971      no   cellular   

       day month  duration  campaign  pdays  previous poutcome  y  
0        5   may       261         1     -1         0  unknown  0  
1        5   may       151         1     -1         0  unknown  0  
2        5   may        76         1     -1         0  unknown  0  
3        5   may        92         1     -1         0  unknown  0  
4        5   may       198         1     -1         0  unknown  0  
...    ...   ...       ...       ...    ...       ...      ... ..  
45206   17   nov       977         3     -1         0  unknown  1  
45207   17   nov       456         2     -1         0  unknown  1  
45208   17   nov      1127         5    184         3  success  1  
45209   17   nov       508         4     -1         0  unknown  0  
45210   17   nov       361         2    188        11    other  0  

[45211 rows x 15 columns]

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
df_full_train, df_test = train_test_split(new_df, random_state= 42, test_size= .2) 

In [14]:
len(df_full_train), len(df_test)

(36168, 9043)

In [15]:
df_train, df_val = train_test_split(df_full_train, random_state= 42, test_size= .25)

In [16]:
len(df_train), len(df_val), len(df_test)

(27126, 9042, 9043)

In [17]:
y_train = df_train.y.values
y_train

array([0, 0, 0, ..., 0, 1, 0])

In [18]:
del df_train["y"]

In [19]:
df_train

age            job   marital  education  balance housing   contact  \
20326   32     technician    single   tertiary     1100     yes  cellular   
24301   38   entrepreneur   married  secondary        0     yes  cellular   
38618   49    blue-collar   married  secondary     3309     yes  cellular   
18909   37      housemaid   married    primary     2410      no  cellular   
23081   31  self-employed   married   tertiary     3220      no  cellular   
...    ...            ...       ...        ...      ...     ...       ...   
13264   27       services    single  secondary      167      no  cellular   
28829   40     technician    single   tertiary      693      no  cellular   
3844    54     technician  divorced  secondary        0     yes   unknown   
15597   25       services    single  secondary     2311      no  cellular   
22987   30     management    single   tertiary       15      no  cellular   

       day month  duration  campaign  pdays  previous poutcome  
20326   11   aug        67         1     -1         0  unknown  
24301   17   nov       258         1     -1         0  unknown  
38618   15   may       349         2     -1         0  unknown  
18909    4   aug       315         1     -1         0  unknown  
23081   26   aug        74         4     -1         0  unknown  
...    ...   ...       ...       ...    ...       ...      ...  
13264    8   jul       606         2     -1         0  unknown  
28829   30   jan       427         1     -1         0  unknown  
3844    16   may       161         1     -1         0  unknown  
15597   21   jul      1105         2     -1         0  unknown  
22987   26   aug       252         2     -1         0  unknown  

[27126 rows x 14 columns]

In [20]:
y_val = df_val.y.values
y_val

array([0, 0, 1, ..., 0, 0, 1])

In [21]:
del df_val["y"]
df_val

age            job   marital  education  balance housing    contact  \
11019   38       services  divorced  secondary      -10     yes    unknown   
3403    42     management    single   tertiary     1146     yes    unknown   
12260   43     management   married   tertiary      149     yes    unknown   
45110   50     management   married   tertiary     8205     yes  telephone   
39549   43     management   married   tertiary       79      no   cellular   
...    ...            ...       ...        ...      ...     ...        ...   
17743   47     technician   married  secondary      356      no   cellular   
12796   32         admin.   married  secondary     1604      no   cellular   
27107   45         admin.   married  secondary      857     yes   cellular   
2823    40         admin.   married  secondary      153     yes    unknown   
26490   45  self-employed   married  secondary        7      no   cellular   

       day month  duration  campaign  pdays  previous poutcome  
11019   17   jun        61         2     -1         0  unknown  
3403    15   may        98         2     -1         0  unknown  
12260   23   jun       662         2     -1         0  unknown  
45110   25   oct       293         3    508         1    other  
39549   26   may       640         1     -1         0  unknown  
...    ...   ...       ...       ...    ...       ...      ...  
17743   29   jul        44         5     -1         0  unknown  
12796    7   jul       625         1     -1         0  unknown  
27107   21   nov       169         1     92        20    other  
2823    14   may       159         2     -1         0  unknown  
26490   20   nov       691         1     -1         0  unknown  

[9042 rows x 14 columns]

In [22]:
categorical = df_train.dtypes[df_train.dtypes == "object"]
categorical= categorical.index
categorical = list(categorical)
categorical

['job', 'marital', 'education', 'housing', 'contact', 'month', 'poutcome']

In [23]:
from sklearn.metrics import mutual_info_score

In [24]:
def mutual(series):
    return mutual_info_score(series, y_train).round(2)

In [25]:
df_train[categorical].apply(mutual)

job          0.01
marital      0.00
education    0.00
housing      0.01
contact      0.01
month        0.03
poutcome     0.03
dtype: float64

In [26]:
from sklearn.feature_extraction import DictVectorizer

In [27]:
dv = DictVectorizer(sparse = False)

In [28]:
train_dicts = df_train[categorical + numerical].to_dict(orient = 'records')
train_dicts[1]

{'job': 'entrepreneur',
 'marital': 'married',
 'education': 'secondary',
 'housing': 'yes',
 'contact': 'cellular',
 'month': 'nov',
 'poutcome': 'unknown',
 'age': 38,
 'balance': 0,
 'day': 17,
 'duration': 258,
 'campaign': 1,
 'pdays': -1,
 'previous': 0}

In [29]:
dv.fit(train_dicts)

DictVectorizer(sparse=False)

In [30]:
X_train = dv.transform(train_dicts)
X_train

array([[3.200e+01, 1.100e+03, 1.000e+00, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       [3.800e+01, 0.000e+00, 1.000e+00, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       [4.900e+01, 3.309e+03, 2.000e+00, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       ...,
       [5.400e+01, 0.000e+00, 1.000e+00, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       [2.500e+01, 2.311e+03, 2.000e+00, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       [3.000e+01, 1.500e+01, 2.000e+00, ..., 0.000e+00, 1.000e+00,
        0.000e+00]])

In [31]:
dv.get_feature_names_out()

array(['age', 'balance', 'campaign', 'contact=cellular',
       'contact=telephone', 'contact=unknown', 'day', 'duration',
       'education=primary', 'education=secondary', 'education=tertiary',
       'education=unknown', 'housing=no', 'housing=yes', 'job=admin.',
       'job=blue-collar', 'job=entrepreneur', 'job=housemaid',
       'job=management', 'job=retired', 'job=self-employed',
       'job=services', 'job=student', 'job=technician', 'job=unemployed',
       'job=unknown', 'marital=divorced', 'marital=married',
       'marital=single', 'month=apr', 'month=aug', 'month=dec',
       'month=feb', 'month=jan', 'month=jul', 'month=jun', 'month=mar',
       'month=may', 'month=nov', 'month=oct', 'month=sep', 'pdays',
       'poutcome=failure', 'poutcome=other', 'poutcome=success',
       'poutcome=unknown', 'previous'], dtype=object)

In [32]:
from sklearn.linear_model import LogisticRegression

In [33]:
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)

In [34]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [35]:
val_dicts = df_val.to_dict(orient = "records")
val_dicts[1]

{'age': 42,
 'job': 'management',
 'marital': 'single',
 'education': 'tertiary',
 'balance': 1146,
 'housing': 'yes',
 'contact': 'unknown',
 'day': 15,
 'month': 'may',
 'duration': 98,
 'campaign': 2,
 'pdays': -1,
 'previous': 0,
 'poutcome': 'unknown'}

In [36]:
X_val = dv.transform(val_dicts)
X_val

array([[ 3.800e+01, -1.000e+01,  2.000e+00, ...,  0.000e+00,  1.000e+00,
         0.000e+00],
       [ 4.200e+01,  1.146e+03,  2.000e+00, ...,  0.000e+00,  1.000e+00,
         0.000e+00],
       [ 4.300e+01,  1.490e+02,  2.000e+00, ...,  0.000e+00,  1.000e+00,
         0.000e+00],
       ...,
       [ 4.500e+01,  8.570e+02,  1.000e+00, ...,  0.000e+00,  0.000e+00,
         2.000e+01],
       [ 4.000e+01,  1.530e+02,  2.000e+00, ...,  0.000e+00,  1.000e+00,
         0.000e+00],
       [ 4.500e+01,  7.000e+00,  1.000e+00, ...,  0.000e+00,  1.000e+00,
         0.000e+00]])

In [37]:
y_pred = model.predict(X_val)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [38]:
accuracy = (y_pred == y_val).mean()
accuracy

np.float64(0.9010174740101747)

## Feature elimination

In [39]:
numerical

['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous']

In [40]:
wo_age = ['balance', 'day', 'duration', 'campaign', 'pdays', 'previous']

In [41]:
train_age = df_train[categorical + wo_age].to_dict(orient= "records")
train_age[1]

{'job': 'entrepreneur',
 'marital': 'married',
 'education': 'secondary',
 'housing': 'yes',
 'contact': 'cellular',
 'month': 'nov',
 'poutcome': 'unknown',
 'balance': 0,
 'day': 17,
 'duration': 258,
 'campaign': 1,
 'pdays': -1,
 'previous': 0}

In [42]:
X_age = dv.fit_transform(train_age)
X_age

array([[1.100e+03, 1.000e+00, 1.000e+00, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       [0.000e+00, 1.000e+00, 1.000e+00, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       [3.309e+03, 2.000e+00, 1.000e+00, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       ...,
       [0.000e+00, 1.000e+00, 0.000e+00, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       [2.311e+03, 2.000e+00, 1.000e+00, ..., 0.000e+00, 1.000e+00,
        0.000e+00],
       [1.500e+01, 2.000e+00, 1.000e+00, ..., 0.000e+00, 1.000e+00,
        0.000e+00]])

In [43]:
val_age = df_val[categorical + wo_age].to_dict(orient= "records")
val_age[1]

{'job': 'management',
 'marital': 'single',
 'education': 'tertiary',
 'housing': 'yes',
 'contact': 'unknown',
 'month': 'may',
 'poutcome': 'unknown',
 'balance': 1146,
 'day': 15,
 'duration': 98,
 'campaign': 2,
 'pdays': -1,
 'previous': 0}

In [44]:
X_vage = dv.transform(val_age)
X_vage

array([[-1.000e+01,  2.000e+00,  0.000e+00, ...,  0.000e+00,  1.000e+00,
         0.000e+00],
       [ 1.146e+03,  2.000e+00,  0.000e+00, ...,  0.000e+00,  1.000e+00,
         0.000e+00],
       [ 1.490e+02,  2.000e+00,  0.000e+00, ...,  0.000e+00,  1.000e+00,
         0.000e+00],
       ...,
       [ 8.570e+02,  1.000e+00,  1.000e+00, ...,  0.000e+00,  0.000e+00,
         2.000e+01],
       [ 1.530e+02,  2.000e+00,  0.000e+00, ...,  0.000e+00,  1.000e+00,
         0.000e+00],
       [ 7.000e+00,  1.000e+00,  1.000e+00, ...,  0.000e+00,  1.000e+00,
         0.000e+00]])

In [45]:
model

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [46]:
model.fit(X_age, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [47]:
y_age = model.predict(X_vage)

In [48]:
age_accuracy = (y_age == y_val).mean()
age_accuracy

np.float64(0.9010174740101747)

In [49]:
age_accuracy - accuracy

np.float64(0.0)

In [50]:
numerical
wo_balance = ['age', 'day', 'duration', 'campaign', 'pdays', 'previous']
train_balance = df_train[categorical + wo_balance].to_dict(orient= "records")
X_balance = dv.fit_transform(train_balance)
val_balance = df_val[categorical + wo_balance].to_dict(orient= "records")
X_vbalance = dv.transform(val_balance)

In [51]:
model.fit(X_balance, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [52]:
y_balance = model.predict(X_vbalance)

In [53]:
balance_accuracy = (y_balance == y_val).mean()
balance_accuracy

np.float64(0.9007962840079629)

In [54]:
balance_accuracy- accuracy

np.float64(-0.00022119000221187957)

In [55]:
categorical

['job', 'marital', 'education', 'housing', 'contact', 'month', 'poutcome']

In [56]:
wo_marital = ['job', 'education', 'housing', 'contact', 'month', 'poutcome']
train_marital = df_train[wo_marital + numerical].to_dict(orient= "records")
X_marital = dv.fit_transform(train_marital)
val_marital = df_val[wo_marital + numerical].to_dict(orient= "records")
X_vmarital = dv.transform(val_marital)

In [57]:
model.fit(X_marital, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [58]:
y_marital = model.predict(X_vmarital)

In [59]:
marital_accuracy = (y_marital == y_val).mean()
marital_accuracy

np.float64(0.9002433090024331)

In [60]:
marital_accuracy -accuracy

np.float64(-0.000774165007741634)

In [61]:
numerical

['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous']

In [97]:
model1 = LogisticRegression(max_iter=1000, random_state=42, solver='liblinear', C= 0.01)
model1.fit(X_train, y_train)

LogisticRegression(C=0.01, max_iter=1000, random_state=42, solver='liblinear')

In [98]:
y_pred = model1.predict(X_val)

In [99]:
(y_pred == y_val).mean()

np.float64(0.8986949789869498)

In [100]:
accuracy

np.float64(0.9010174740101747)

In [101]:
model2 = LogisticRegression(max_iter=1000, random_state=42, solver='liblinear', C= 0.1)
model2.fit(X_train, y_train)
y_pred = model2.predict(X_val)
(y_pred == y_val).mean()

np.float64(0.900464499004645)

In [102]:
model3 = LogisticRegression(max_iter=1000, random_state=42, solver='liblinear', C= 1)
model3.fit(X_train, y_train)
y_pred = model3.predict(X_val)
(y_pred == y_val).mean()

np.float64(0.9010174740101747)

In [103]:
model4 = LogisticRegression(max_iter=1000, random_state=42, solver='liblinear', C= 10)
model4.fit(X_train, y_train)
y_pred = model4.predict(X_val)
(y_pred == y_val).mean()

np.float64(0.9012386640123866)

In [104]:
model5 = LogisticRegression(max_iter=1000, random_state=42, solver='liblinear', C= 100)
model5.fit(X_train, y_train)
y_pred = model5.predict(X_val)
(y_pred == y_val).mean()

np.float64(0.9012386640123866)