# ASSIGNMENT
### Question 1: What's the version of Pandas that you installed?

In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.2.3'

In [5]:
df = pd.read_csv("laptops.csv", index_col= 0)
df

Status   Brand  \
Laptop                                                                    
ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core ...          New    Asus   
Alurin Go Start Intel Celeron N4020/8GB/256GB S...          New  Alurin   
ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core ...          New    Asus   
MSI Katana GF66 12UC-082XES Intel Core i7-12700...          New     MSI   
HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB ...          New      HP   
...                                                         ...     ...   
Razer Blade 17 FHD 360Hz Intel Core i7-11800H/1...  Refurbished   Razer   
Razer Blade 17 FHD 360Hz Intel Core i7-11800H/1...  Refurbished   Razer   
Razer Blade 17 FHD 360Hz Intel Core i7-11800H/3...  Refurbished   Razer   
Razer Book 13 Intel Evo Core i7-1165G7/16GB/1TB...  Refurbished   Razer   
Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/2...  Refurbished   Razer   

                                                         Model  \
Laptop                                                           
ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core ...  ExpertBook   
Alurin Go Start Intel Celeron N4020/8GB/256GB S...          Go   
ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core ...  ExpertBook   
MSI Katana GF66 12UC-082XES Intel Core i7-12700...      Katana   
HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB ...         15S   
...                                                        ...   
Razer Blade 17 FHD 360Hz Intel Core i7-11800H/1...       Blade   
Razer Blade 17 FHD 360Hz Intel Core i7-11800H/1...       Blade   
Razer Blade 17 FHD 360Hz Intel Core i7-11800H/3...       Blade   
Razer Book 13 Intel Evo Core i7-1165G7/16GB/1TB...        Book   
Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/2...        Book   

                                                                  CPU  RAM  \
Laptop                                                                       
ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core ...      Intel Core i5    8   
Alurin Go Start Intel Celeron N4020/8GB/256GB S...      Intel Celeron    8   
ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core ...      Intel Core i3    8   
MSI Katana GF66 12UC-082XES Intel Core i7-12700...      Intel Core i7   16   
HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB ...      Intel Core i5   16   
...                                                               ...  ...   
Razer Blade 17 FHD 360Hz Intel Core i7-11800H/1...      Intel Core i7   16   
Razer Blade 17 FHD 360Hz Intel Core i7-11800H/1...      Intel Core i7   16   
Razer Blade 17 FHD 360Hz Intel Core i7-11800H/3...      Intel Core i7   32   
Razer Book 13 Intel Evo Core i7-1165G7/16GB/1TB...  Intel Evo Core i7   16   
Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/2...  Intel Evo Core i7   16   

                                                    Storage Storage type  \
Laptop                                                                     
ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core ...      512          SSD   
Alurin Go Start Intel Celeron N4020/8GB/256GB S...      256          SSD   
ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core ...      256          SSD   
MSI Katana GF66 12UC-082XES Intel Core i7-12700...     1000          SSD   
HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB ...      512          SSD   
...                                                     ...          ...   
Razer Blade 17 FHD 360Hz Intel Core i7-11800H/1...     1000          SSD   
Razer Blade 17 FHD 360Hz Intel Core i7-11800H/1...     1000          SSD   
Razer Blade 17 FHD 360Hz Intel Core i7-11800H/3...     1000          SSD   
Razer Book 13 Intel Evo Core i7-1165G7/16GB/1TB...     1000          SSD   
Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/2...      256          SSD   

                                                         GPU  Screen Touch  \
Laptop                                                                       
ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core ...       NaN  

### Question 2: How many records are in the dataset?

In [7]:
len(df)

2160

### Question 3: How many laptop brands are presented in the dataset?

In [8]:
df.Brand.nunique()

27

### Question 4: How many columns in the dataset have missing values?

In [13]:
df.isnull().sum()

Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

## Question 5: What's the maximum final price of Dell notebooks in the dataset?

In [21]:
df.groupby("Brand").count()

Status  Model  CPU  RAM  Storage  Storage type  GPU  Screen  \
Brand                                                                           
Acer                 137    137  137  137      137           137   51     136   
Alurin                29     29   29   29       29            25    0      29   
Apple                116    116  116  116      116           105    9     116   
Asus                 415    415  415  415      415           409  168     415   
Deep Gaming            8      8    8    8        8             8    8       8   
Dell                  84     84   84   84       84            84    6      84   
Denver                 1      1    1    1        1             1    0       1   
Dynabook Toshiba      19     19   19   19       19            19    0      19   
Gigabyte              48     48   48   48       48            48   46      48   
HP                   368    368  368  368      368           361   87     367   
Innjoo                 6      6    6    6        6             6    0       6   
Jetwing                1      1    1    1        1             1    0       1   
LG                    32     32   32   32       32            32    7      32   
Lenovo               366    366  366  366      366           363   74     364   
MSI                  308    308  308  308      308           308  256     308   
Medion                32     32   32   32       32            30   10      32   
Microsoft             77     77   77   77       77            74    4      77   
Millenium              2      2    2    2        2             2    2       2   
PcCom                 24     24   24   24       24            22   24      24   
Primux                 8      8    8    8        8             8    0       8   
Prixton                3      3    3    3        3             1    0       3   
Razer                 37     37   37   37       37            37   35      37   
Realme                 1      1    1    1        1             1    0       1   
Samsung               22     22   22   22       22            21    2      22   
Thomson                4      4    4    4        4             3    0       4   
Toshiba                1      1    1    1        1             1    0       1   
Vant                  11     11   11   11       11            11    0      11   

                  Touch  Final Price  
Brand                                 
Acer                137          137  
Alurin               29           29  
Apple               116          116  
Asus                415          415  
Deep Gaming           8            8  
Dell                 84           84  
Denver                1            1  
Dynabook Toshiba     19           19  
Gigabyte             48           48  
HP                  368          368  
Innjoo                6            6  
Jetwing               1            1  
LG                   32           32  
Lenovo              366          366  
MSI                 308          308  
Medion               32           32  
Microsoft            77           77  
Millenium             2            2  
PcCom                24           24  
Primux                8            8  
Prixton               3            3  
Razer                37           37  
Realme                1            1  
Samsung              22           22  
Thomson               4            4  
Toshiba               1            1  
Vant                 11           11

In [35]:
dell= df[df["Brand"] == "Dell"]
dell

Status Brand  \
Laptop                                                                  
Dell Vostro 3510 Intel Core i3-1115G4/8 GB/256G...          New  Dell   
Dell Vostro 3510 Intel Core i5-1135G7/8 GB/256G...          New  Dell   
Dell Vostro 3520 Intel Core i7-1255U/16GB/512GB...          New  Dell   
Dell Latitude 3520 Intel Core i5-1135G7/8GB/256...          New  Dell   
Dell Vostro 3510 Intel Core i5-1135G7/16 GB/512...          New  Dell   
...                                                         ...   ...   
Dell Vostro 5301 Intel Core i5-1135G7/8GB/256GB...  Refurbished  Dell   
Dell Vostro 5301 Intel Core i5-1135G7/8GB/512GB...  Refurbished  Dell   
Dell Vostro 5502 Intel Core i5-1135G7/8GB/512GB...  Refurbished  Dell   
Dell XPS 13 9300 Intel Core i5-1035G1/8GB/512GB...  Refurbished  Dell   
Dell XPS 7390 Intel Core i7-10510U/16GB/512GB S...  Refurbished  Dell   

                                                       Model            CPU  \
Laptop                                                                        
Dell Vostro 3510 Intel Core i3-1115G4/8 GB/256G...    Vostro  Intel Core i3   
Dell Vostro 3510 Intel Core i5-1135G7/8 GB/256G...    Vostro  Intel Core i5   
Dell Vostro 3520 Intel Core i7-1255U/16GB/512GB...    Vostro  Intel Core i7   
Dell Latitude 3520 Intel Core i5-1135G7/8GB/256...  Latitude  Intel Core i5   
Dell Vostro 3510 Intel Core i5-1135G7/16 GB/512...    Vostro  Intel Core i5   
...                                                      ...            ...   
Dell Vostro 5301 Intel Core i5-1135G7/8GB/256GB...    Vostro  Intel Core i5   
Dell Vostro 5301 Intel Core i5-1135G7/8GB/512GB...    Vostro  Intel Core i5   
Dell Vostro 5502 Intel Core i5-1135G7/8GB/512GB...    Vostro  Intel Core i5   
Dell XPS 13 9300 Intel Core i5-1035G1/8GB/512GB...       XPS  Intel Core i5   
Dell XPS 7390 Intel Core i7-10510U/16GB/512GB S...       XPS  Intel Core i7   

                                                    RAM  Storage Storage type  \
Laptop                                                                          
Dell Vostro 3510 Intel Core i3-1115G4/8 GB/256G...    8      256          SSD   
Dell Vostro 3510 Intel Core i5-1135G7/8 GB/256G...    8      256          SSD   
Dell Vostro 3520 Intel Core i7-1255U/16GB/512GB...   16      512          SSD   
Dell Latitude 3520 Intel Core i5-1135G7/8GB/256...    8      256          SSD   
Dell Vostro 3510 Intel Core i5-1135G7/16 GB/512...   16      512          SSD   
...                                                 ...      ...          ...   
Dell Vostro 5301 Intel Core i5-1135G7/8GB/256GB...    8      256          SSD   
Dell Vostro 5301 Intel Core i5-1135G7/8GB/512GB...    8      512          SSD   
Dell Vostro 5502 Intel Core i5-1135G7/8GB/512GB...    8      512          SSD   
Dell XPS 13 9300 Intel Core i5-1035G1/8GB/512GB...    8      512          SSD   
Dell XPS 7390 Intel Core i7-10510U/16GB/512GB S...   16      512          SSD   

                                                    GPU  Screen Touch  \
Laptop                                                                  
Dell Vostro 3510 Intel Core i3-1115G4/8 GB/256G...  NaN    15.6    No   
Dell Vostro 3510 Intel Core i5-1135G7/8 GB/256G...  NaN    15.6    No   
Dell Vostro 3520 Intel Core i7-1255U/16GB/512GB...  NaN    15.6    No   
Dell Latitude 3520 Intel Core i5-1135G7/8GB/256...  NaN    15.6    No   
Dell Vostro 3510 Intel Core i5-1135G7/16 GB/512...  NaN    15.6    No   
...                                                 ...     ...   ...   
Dell Vostro 5301 Intel Core i5-1135G7/8GB/256GB...  NaN    13.3    No   
Dell Vostro 5301 Intel Core i5-1135G7/8GB/512GB...  NaN    13.3    No   
Dell Vostro 5502 Intel Core i5-1135G7/8GB/512GB...  NaN    15.6    No   
Dell XPS 13 9300 Intel Core i5-1035G1/8GB/512GB...  NaN    13.4    No   
Dell XPS 7390 Intel Core i7-10510U/16GB/512GB S...  NaN    13.3    No   

                                                    Final Price  
Laptop   

In [23]:
dell["Final Price"].max()

np.float64(3936.0)

### Q6. Median value of Screen

In [53]:
# Find the median value of Screen column in the dataset.
screen = df[["Screen"]]
print(screen.median())
# Next, calculate the most frequent value of the same Screen column.
freq = screen.mode()
print(freq)

Screen    15.6
dtype: float64
   Screen
0    15.6


In [56]:
# Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
newscreen= screen.fillna(15.6)

In [58]:
newscreen.median()

Screen    15.6
dtype: float64

### Q7: Sum of weights

In [59]:
# Select all the "Innjoo" laptops from the datase
df.index

Index(['ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core i5-1235U/8GB/512GB SSD/15.6"',
       'Alurin Go Start Intel Celeron N4020/8GB/256GB SSD/15.6"',
       'ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core i3-1215U/8GB/256GB SSD/15.6"',
       'MSI Katana GF66 12UC-082XES Intel Core i7-12700H/16GB/1TB SSD/RTX3050/15.6"',
       'HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB SSD/15.6"',
       'MSI Crosshair 17 C12VF-264XES Intel Core i7-12650H/32GB/1TB SSD/RTX 4060/17.3"',
       'Lenovo Thinkpad E14 Gen 4 AMD Ryzen 5 5625U/8GB/256GB SSD/14"',
       'ASUS VivoBook 15 F515JA-EJ2882W Intel Core i7-1065G7/8GB/512GB SSD/15.6"',
       'Medion Akoya E15415 Intel Core i5-10210U/8GB/256GB SSD/15.6"',
       'HP Victus 16-d1038ns Intel Core i7-12700H/16GB/512GB SSD/RTX 3050/16.1"',
       ...
       'Razer Blade 15 Advanced Model QHD Intel Core i7-11800H/32 GB/1TB SSD/RTX 3080/15.6"',
       'Razer Blade 15 Advanced Model QHD Intel Core i7-11800H/32GB/1TB SSD/RTX 3080/15.6"',
       'Razer 

In [64]:
#Select all the "Innjoo" laptops from the datase
injoo = df[df.Brand == "Innjoo"]
injoo

Status   Brand Model  \
Laptop                                                                    
InnJoo Voom Excellence Intel Celeron N4020/8GB/...    New  Innjoo  Voom   
InnJoo Voom Excellence Pro Intel Celeron N4020/...    New  Innjoo  Voom   
Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/1...    New  Innjoo  Voom   
Innjoo Voom Laptop Max Intel Celeron N3350/6GB/...    New  Innjoo  Voom   
Innjoo Voom Laptop Pro Intel Celeron N3350/6GB/...    New  Innjoo  Voom   
Innjoo Voom Pro Intel Celeron N3350/6GB/128GB e...    New  Innjoo  Voom   

                                                              CPU  RAM  \
Laptop                                                                   
InnJoo Voom Excellence Intel Celeron N4020/8GB/...  Intel Celeron    8   
InnJoo Voom Excellence Pro Intel Celeron N4020/...  Intel Celeron    8   
Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/1...  Intel Celeron    4   
Innjoo Voom Laptop Max Intel Celeron N3350/6GB/...  Intel Celeron    6   
Innjoo Voom Laptop Pro Intel Celeron N3350/6GB/...  Intel Celeron    6   
Innjoo Voom Pro Intel Celeron N3350/6GB/128GB e...  Intel Celeron    6   

                                                    Storage Storage type  GPU  \
Laptop                                                                          
InnJoo Voom Excellence Intel Celeron N4020/8GB/...      256          SSD  NaN   
InnJoo Voom Excellence Pro Intel Celeron N4020/...      512          SSD  NaN   
Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/1...       64         eMMC  NaN   
Innjoo Voom Laptop Max Intel Celeron N3350/6GB/...       64         eMMC  NaN   
Innjoo Voom Laptop Pro Intel Celeron N3350/6GB/...      128          SSD  NaN   
Innjoo Voom Pro Intel Celeron N3350/6GB/128GB e...      128         eMMC  NaN   

                                                    Screen Touch  Final Price  
Laptop                                                                         
InnJoo Voom Excellence Intel Celeron N4020/8GB/...    15.6    No       311.37  
InnJoo Voom Excellence Pro Intel Celeron N4020/...    15.6    No       392.55  
Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/1...    14.1    No       251.40  
Innjoo Voom Laptop Max Intel Celeron N3350/6GB/...    14.1    No       383.61  
Innjoo Voom Laptop Pro Intel Celeron N3350/6GB/...    14.1    No       317.02  
Innjoo Voom Pro Intel Celeron N3350/6GB/128GB e...    14.1    No       431.38

In [67]:
#Select only columns RAM, Storage, Screen.
newdf= injoo[["RAM", "Storage","Screen"]]
newdf

RAM  Storage  Screen
Laptop                                                                  
InnJoo Voom Excellence Intel Celeron N4020/8GB/...    8      256    15.6
InnJoo Voom Excellence Pro Intel Celeron N4020/...    8      512    15.6
Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/1...    4       64    14.1
Innjoo Voom Laptop Max Intel Celeron N3350/6GB/...    6       64    14.1
Innjoo Voom Laptop Pro Intel Celeron N3350/6GB/...    6      128    14.1
Innjoo Voom Pro Intel Celeron N3350/6GB/128GB e...    6      128    14.1

In [74]:
# Get the underlying NumPy array. Let's call it X.
X = newdf.values
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [75]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
Xt = x.T
Xt

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [79]:
import numpy as np
XtX =np.dot(Xt, X)
XtX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [80]:
#Compute the inverse of XTX.
inverse= np.linalg.inv(XtX)
inverse

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [81]:
#Create an array y with values [1100, 1300, 800, 900, 1000, 1100]
y= np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [83]:
#Multiply the inverse of XTX with the transpose of X and then multiply the result by y. Call the result w.
mult = np.dot(inverse, Xt)
w= np.dot(mult, y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [84]:
#What's the sum of all the elements of the result?
np.sum(w)

np.float64(91.2998806299555)